<?php
include_once( get_stylesheet_directory() . '/acf/acf.php' );

if( function_exists('acf_add_local_field_group') ) {

	acf_add_local_field_group(array (
		'key' => 'group_5926a86b62003',
		'title' => 'Studio Information',
		'fields' => array (
			array (
				'key' => 'field_5926a93599796',
				'label' => 'Studio',
				'name' => 'studio',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5926a9e6fef64',
				'label' => 'Studio Director',
				'name' => 'director',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5926a9eafef65',
				'label' => 'Invitees',
				'name' => 'invitees',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5926a9f5fef66',
				'label' => 'Address',
				'name' => 'address',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5926a9fdfef67',
				'label' => 'City',
				'name' => 'city',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5926aa03fef68',
				'label' => 'State',
				'name' => 'state',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5926aa08fef69',
				'label' => 'Zipcode',
				'name' => 'zipcode',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5926aa0dfef6a',
				'label' => 'Country',
				'name' => 'country',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5926aa16fef6b',
				'label' => 'Phone',
				'name' => 'phone',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_594454a63f96b',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_5967c2c787219',
				'label' => 'Cell',
				'name' => 'cell',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5967c2e98721a',
				'label' => 'Studio Contact Name',
				'name' => 'contact',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'user_form',
					'operator' => '==',
					'value' => 'edit',
				),
				array (
					'param' => 'user_role',
					'operator' => '==',
					'value' => 'studio',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_59677fb72662b',
		'title' => 'Personal Information',
		'fields' => array (
			array (
				'key' => 'field_59678112603cc',
				'label' => 'Name',
				'name' => 'name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_59678128603cd',
				'label' => 'Date of Birth',
				'name' => 'birth_date',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5967813a603ce',
				'label' => 'Parent\'s Name',
				'name' => 'parent',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5967813f603cf',
				'label' => 'Studio Name',
				'name' => 'studio',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_59678166603d0',
				'label' => 'Address',
				'name' => 'address',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5967816a603d1',
				'label' => 'City',
				'name' => 'city',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5967821d603d2',
				'label' => 'State',
				'name' => 'state',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_59678225603d3',
				'label' => 'Zip Code',
				'name' => 'zipcode',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_5967822e603d4',
				'label' => 'Country',
				'name' => 'country',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_59678248603d5',
				'label' => 'Cell',
				'name' => 'cell',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'readonly' => 0,
				'disabled' => 0,
			),
			array (
				'key' => 'field_59678252603d6',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'email',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'user_form',
					'operator' => '==',
					'value' => 'edit',
				),
				array (
					'param' => 'user_role',
					'operator' => '==',
					'value' => 'individual',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_598d69e58299d',
		'title' => 'Mailchimp',
		'fields' => array (
			array (
				'key' => 'field_598d6a2eb84ed',
				'label' => 'List ID',
				'name' => 'list_id',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'ts_tour',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

	acf_add_local_field_group(array (
		'key' => 'group_59c21e47cc2b5',
		'title' => 'Workshop Schedule Details',
		'fields' => array (
			array (
				'key' => 'field_59e474d5debee',
				'label' => '',
				'name' => 'publish',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Publish Schedule to Website and User Portal',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array (
				'key' => 'field_59ce6df7ae6eb',
				'label' => 'Tour City',
				'name' => 'event_city',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'post_type' => array (
					0 => 'ts_tour',
				),
				'taxonomy' => array (
				),
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'id',
				'ui' => 1,
			),
			array (
				'key' => 'field_59ce7b0e2bdcd',
				'label' => '',
				'name' => 'event_schedules',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 3,
				'max' => 3,
				'layout' => 'block',
				'button_label' => 'Add Day',
				'sub_fields' => array (
					array (
						'key' => 'field_59ce7b4a2bdce',
						'label' => 'Day',
						'name' => 'day',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '15',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
                    array (
                        'key' => 'field_34ce7b4a2bdce',
                        'label' => 'Change Header',
                        'name' => 'column_1',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '13',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Seniors',
                        'placeholder' => 'Seniors',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_74ce7b4a2bdce',
                        'label' => 'Change Header',
                        'name' => 'column_2',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '13',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Teens',
                        'placeholder' => 'Teens',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_44ce7b4a2bdce',
                        'label' => 'Change Header',
                        'name' => 'column_3',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '13',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Juniors',
                        'placeholder' => 'Juniors',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_54ce7b4a2bdce',
                        'label' => 'Change Header',
                        'name' => 'column_4',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '13',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Minis',
                        'placeholder' => 'Minis',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_64ce7b4a2bdce',
                        'label' => 'Change Header',
                        'name' => 'column_5',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '13',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Munchkins/Pro/Teachers',
                        'placeholder' => 'Munchkins/Pro/Teachers',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
					array (
						'key' => 'field_59ce7b5b2bdcf',
						'label' => 'Schedule',
						'name' => 'lineup',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'collapsed' => '',
						'min' => 1,
						'max' => 0,
						'layout' => 'table',
						'button_label' => 'Add Row',
						'sub_fields' => array (
							array (
								'key' => 'field_59ce7cc0f7a30',
								'label' => 'Time',
								'name' => 'time',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_59ce7cd1f7a31',
								'label' => 'Seniors',
								'name' => 'seniors',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_59ce7cd8f7a32',
								'label' => 'Teens',
								'name' => 'teens',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_59ce7cdef7a33',
								'label' => 'Juniors',
								'name' => 'juniors',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_59ce7ce3f7a34',
								'label' => 'Minis',
								'name' => 'minis',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_59ce7ce9f7a35',
								'label' => 'Munchkins/Pro/Teachers',
								'name' => 'munchkinsproteachers',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array (
								'key' => 'field_59ce7cecf7a36',
								'label' => 'Columns',
								'name' => 'columns',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array (
									'Col_1_5 Highlighted' => 'Col_1_5 Highlighted',
									'Col_1_5' => 'Col_1_5',
									'Col_1_4_1' => 'Col_1_4_1',
									'Col_1_2_2_1' => 'Col_1_2_2_1',
									'Col_1_2_1_1_1' => 'Col_1_2_1_1_1',
								),
								'default_value' => array (
								),
								'allow_null' => 1,
								'multiple' => 0,
								'ui' => 0,
								'ajax' => 0,
								'return_format' => 'value',
								'placeholder' => '',
							),
						),
					),
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'ts_event',
				),
				array (
					'param' => 'post_taxonomy',
					'operator' => '==',
					'value' => 'ts_schedules_type:Workshop',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

    acf_add_local_field_group(array (
        'key' => 'group_59d2674ac404f',
        'title' => 'Competition Schedule Details',
        'fields' => array (
			array (
				'key' => 'field_59e474d5debed',
				'label' => '',
				'name' => 'publish',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => 'Publish Schedule to Website and User Portal',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
            array (
                'key' => 'field_59d2697cc385f',
                'label' => 'Tour City',
                'name' => 'event_city',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array (
                    0 => 'ts_tour',
                ),
                'taxonomy' => array (
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'return_format' => 'id',
                'ui' => 1,
            ),
            array (
                'key' => 'field_59d2674b099e9',
                'label' => '',
                'name' => 'competition_event_schedules',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 1,
                'max' => 1,
                'layout' => 'block',
                'button_label' => 'Add Day',
                'sub_fields' => array (
                    array (
                        'key' => 'field_59d2674f77b98',
						'label' => 'Start Date/Time',
						'name' => 'day',
						'type' => 'date_time_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'display_format' => 'F j, Y g:i a',
						'return_format' => 'F j, Y g:i a',
						'first_day' => 0,
                    ),
                    array (
                        'key' => 'field_59d2674f77f7b',
                        'label' => 'Schedule',
                        'name' => 'lineup',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 1,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => 'Add Row',
		                'sub_fields' => array (
		                    array (
		                        'key' => 'field_59d2674f9703c',
		                        'label' => 'Number',
		                        'name' => 'number',
		                        'type' => 'text',
		                        'instructions' => '',
		                        'required' => 0,
		                        'conditional_logic' => 0,
		                        'wrapper' => array (
		                            'width' => '5',
		                            'class' => '',
		                            'id' => '',
		                        ),
		                        'default_value' => '',
		                        'placeholder' => '',
		                        'prepend' => '',
		                        'append' => '',
		                        'maxlength' => '',
		                    ),
		                    array (
		                        'key' => 'field_59d2674f973fa',
		                        'label' => 'Time Start',
		                        'name' => 'time_start',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '8',
									'class' => '',
									'id' => '',
								),
		                        'default_value' => '',
		                        'placeholder' => '',
		                        'prepend' => '',
		                        'append' => '',
		                        'maxlength' => '',
		                    ),
							array (
								'key' => 'field_5a0aecd9b6bb4',
								'label' => 'Time End',
								'name' => 'time_end',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '8',
									'class' => '',
									'id' => '',
								),
		                        'default_value' => '',
		                        'placeholder' => '',
		                        'prepend' => '',
		                        'append' => '',
		                        'maxlength' => '',
							),
		                    array (
		                        'key' => 'field_59d2674f97bd8',
		                        'label' => 'Routine',
		                        'name' => 'routine',
		                        'type' => 'post_object',
		                        'instructions' => '',
		                        'required' => 0,
		                        'conditional_logic' => 0,
		                        'wrapper' => array (
		                            'width' => '15',
		                            'class' => '',
		                            'id' => '',
		                        ),
		                        'post_type' => array (
		                            0 => 'ts_routine',
		                        ),
		                        'taxonomy' => array (
		                        ),
		                        'allow_null' => 0,
		                        'multiple' => 0,
		                        'return_format' => 'id',
		                        'ui' => 1,
		                    ),
		                    array (
		                        'key' => 'field_59d2674f97fbb',
		                        'label' => 'Age Division',
		                        'name' => 'age_division',
		                        'type' => 'text',
		                        'instructions' => '',
		                        'required' => 0,
		                        'conditional_logic' => 0,
		                        'wrapper' => array (
		                            'width' => '10',
		                            'class' => '',
		                            'id' => '',
		                        ),
		                        'default_value' => '',
		                        'placeholder' => '',
		                        'prepend' => '',
		                        'append' => '',
		                        'maxlength' => '',
		                    ),
		                    array (
		                        'key' => 'field_59d2674f9839c',
		                        'label' => 'Category',
		                        'name' => 'category',
		                        'type' => 'text',
		                        'instructions' => '',
		                        'required' => 0,
		                        'conditional_logic' => 0,
		                        'wrapper' => array (
		                            'width' => '10',
		                            'class' => '',
		                            'id' => '',
		                        ),
		                        'default_value' => '',
		                        'placeholder' => '',
		                        'prepend' => '',
		                        'append' => '',
		                        'maxlength' => '',
		                    ),
		                    array (
		                        'key' => 'field_59d2674f9878a',
		                        'label' => 'Genre',
		                        'name' => 'genre',
		                        'type' => 'text',
		                        'instructions' => '',
		                        'required' => 0,
		                        'conditional_logic' => 0,
		                        'wrapper' => array (
		                            'width' => '10',
		                            'class' => '',
		                            'id' => '',
		                        ),
		                        'default_value' => '',
		                        'placeholder' => '',
		                        'prepend' => '',
		                        'append' => '',
		                        'maxlength' => '',
		                    ),
		                    array (
		                        'key' => 'field_59d2674f977de',
		                        'label' => 'Studio',
		                        'name' => 'studio',
		                        'type' => 'text',
		                        'instructions' => '',
		                        'required' => 0,
		                        'conditional_logic' => 0,
		                        'wrapper' => array (
		                            'width' => '18',
		                            'class' => '',
		                            'id' => '',
		                        ),
		                        'default_value' => '',
		                        'placeholder' => '',
		                        'prepend' => '',
		                        'append' => '',
		                        'maxlength' => '',
		                    ),
		                    array (
		                        'key' => 'field_59d2674f98ba4',
		                        'label' => 'Row Type',
		                        'name' => 'action',
		                        'type' => 'select',
		                        'instructions' => '',
		                        'required' => 0,
		                        'conditional_logic' => 0,
		                        'wrapper' => array (
		                            'width' => '12',
		                            'class' => '',
		                            'id' => '',
		                        ),
		                        'choices' => array (
		                            'Normal' => 'Normal',
		                            'Judges Break' => 'Judges Break',
		                            'Awards' => 'Awards',
		                            'Day' => 'Day',
		                        ),
		                        'default_value' => array (
		                        ),
		                        'allow_null' => 0,
		                        'multiple' => 0,
		                        'ui' => 0,
		                        'ajax' => 0,
		                        'return_format' => 'value',
		                        'placeholder' => '',
		                    ),
		                ),

                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'ts_event',
                ),
				array (
					'param' => 'post_taxonomy',
					'operator' => '==',
					'value' => 'ts_schedules_type:Competition',
				),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'the_content',
        ),
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_19d2674ac404f',
        'title' => 'Score Details',
        'fields' => array (
            array (
                'key' => 'field_19d2697cc385f',
                'label' => 'Tour City',
                'name' => 'event_city',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array (
                    0 => 'ts_tour',
                ),
                'taxonomy' => array (
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'return_format' => 'id',
                'ui' => 1,
            ),
            array (
                'key' => 'field_19d2674b099e9',
                'label' => 'Tour Scores',
                'name' => 'tour_scores',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 1,
                'max' => 0,
                'layout' => 'block',
                'button_label' => 'Add Score',
                'sub_fields' => array (
                    array (
                        'key' => 'field_19d2674f77b98',
                        'label' => 'Day',
                        'name' => 'day',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '20',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'd/m/Y',
                        'return_format' => 'd/m/Y',
                        'first_day' => 1,
                        'disabled' => 1,
                    ),
                    array (
                        'key' => 'field_19d2674f77f7b',
                        'label' => 'Schedule',
                        'name' => 'lineup',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 1,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => 'Add Row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_19d2674f9703c',
                                'label' => 'Number',
                                'name' => 'number',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '5',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'disabled' => 1,
                            ),
                            array (
                                'key' => 'field_19d2674f973fa',
                                'label' => 'Time',
                                'name' => 'time',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '8',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'disabled' => 1,
                            ),
                            array (
                                'key' => 'field_19d2674f977de',
                                'label' => 'Studio',
                                'name' => 'studio',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '18',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                                'disabled' => 1,
                            ),
                            array (
                                'key' => 'field_19d2674f97bd8',
                                'label' => 'Routine',
                                'name' => 'routine',
                                'type' => 'post_object',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '15',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'post_type' => array (
                                    0 => 'ts_routine',
                                ),
                                'taxonomy' => array (
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'return_format' => 'id',
                                'ui' => 1,
                            ),
                            array (
                                'key' => 'field_19d2674f97fbb',
                                'label' => 'Age Division',
                                'name' => 'age_division',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '8',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'Munchkin' => 'Munchkin',
                                    'Mini' => 'Mini',
                                    'Junior' => 'Junior',
                                    'Teen' => 'Teen',
                                    'Senior' => 'Senior',
                                    'Pro' => 'Pro',
                                    'Teacher' => 'Teacher',
                                ),
                                'default_value' => array (
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                                'disabled' => 1,
                            ),
                            array (
                                'key' => 'field_19d2674f9839c',
                                'label' => 'Category',
                                'name' => 'category',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '8',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'Solo' => 'Solo',
                                    'Duo/Trio' => 'Duo/Trio',
                                    'Small Group' => 'Small Group',
                                    'Large Group' => 'Large Group',
                                    'Line' => 'Line',
                                    'Production' => 'Production',
                                ),
                                'default_value' => array (
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                                'disabled' => 1,
                            ),
                            array (
                                'key' => 'field_19d2674f9878a',
                                'label' => 'Genre',
                                'name' => 'genre',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '10',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'Ballet' => 'Ballet',
                                    'Jazz' => 'Jazz',
                                    'Hip-Hop' => 'Hip-Hop',
                                    'Contemporary' => 'Contemporary',
                                    'Lyrical' => 'Lyrical',
                                    'Tap' => 'Tap',
                                    'Musical Theater' => 'Musical Theater',
                                    'Open' => 'Open',
                                    'Improv' => 'Improv',
                                ),
                                'default_value' => array (
                                ),
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'return_format' => 'value',
                                'placeholder' => '',
                                'disabled' => 1,
                            ),
                            array (
                                'key' => 'field_89e4b7c4a3479',
                                'label' => 'Judge 1 Score',
                                'name' => 'judge_1_score',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '8%',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 0,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                            array (
                                'key' => 'field_79e4b7c4a3479',
                                'label' => 'Judge 2 Score',
                                'name' => 'judge_2_score',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '8%',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 0,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                            array (
                                'key' => 'field_69e4b7c4a3479',
                                'label' => 'Judge 3 Score',
                                'name' => 'judge_3_score',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '8%',
                                    'id' => '',
                                ),
                                'default_value' => 0,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),                            
                            array (
                                'key' => 'field_19e4b7c4a3479',
                                'label' => 'Total Score',
                                'name' => 'score',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => 'hidden',
                                    'id' => '',
                                ),
                                'default_value' => 0,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => '',
                                'max' => '',
                                'step' => '',
                            ),
                        ),
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'ts_score',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'the_content',
        ),
        'active' => 1,
        'description' => '',
    ));

}